version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.820.0
    - 2.834.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.2.1
